# Zsh plugins
[".config/zsh/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".config/zsh/plugins/zsh-history-substring-search"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-history-substring-search/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".config/zsh/plugins/f-sy-h"]
    type = "archive"
    url = "https://github.com/zdharma-continuum/fast-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"


# Vim plugins
[".vim/pack/plugins/start/editorconfig-vim"]
    type = "archive"
    url = "https://github.com/editorconfig/editorconfig-vim/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".vim/pack/plugins/start/vim-airline"]
    type = "archive"
    url = "https://github.com/vim-airline/vim-airline/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".vim/pack/plugins/start/catppuccin"]
    type = "archive"
    url = "https://github.com/catppuccin/vim/archive/main.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".vim/pack/plugins/start/indentLine"]
    type = "archive"
    url = "https://github.com/Yggdroot/indentLine/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"


# Tmux plugins
[".tmux/plugins/tmux-cpu"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tmux-cpu/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".tmux/plugins/catppuccin"]
    type = "archive"
    url = "https://github.com/catppuccin/tmux/archive/main.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
